// <auto-generated />
using System;
using AppointmentScheduler.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppointmentScheduler.API.Data.Migrations
{
    [DbContext(typeof(AppointmentSchedulerContext))]
    [Migration("20220921074151_createdatabase")]
    partial class createdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppointmentScheduler.API.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("AppointmentScheduler.API.Models.AppointmentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("CoachScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AppointmentDetails");
                });

            modelBuilder.Entity("AppointmentScheduler.API.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9499),
                            Name = "Jane Doe",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 2,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9510),
                            Name = "Christy Schumm",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 3,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9511),
                            Name = "Christy Schumm",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 4,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9511),
                            Name = "Christy Schumm",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 5,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9512),
                            Name = "Christy Schumm",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 6,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9513),
                            Name = "Natalia Stanton Jr.",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 7,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9513),
                            Name = "Natalia Stanton Jr.",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 8,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9514),
                            Name = "Natalia Stanton Jr.",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 9,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9515),
                            Name = "Natalia Stanton Jr.",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 10,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9516),
                            Name = "Nola Murazik V",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 11,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9516),
                            Name = "Nola Murazik V",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 12,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9517),
                            Name = "Nola Murazik V",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 13,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9518),
                            Name = "Nola Murazik V",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 14,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9519),
                            Name = "Nola Murazik V",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 15,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9519),
                            Name = "Elyssa O'Kon",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 16,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9520),
                            Name = "Elyssa O'Kon",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 17,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9521),
                            Name = "Elyssa O'Kon",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 18,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9521),
                            Name = "Elyssa O'Kon",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 19,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9522),
                            Name = "Elyssa O'Kon",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 20,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9523),
                            Name = "Elyssa O'Kon",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 21,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9523),
                            Name = "Dr. Geovany Keebler",
                            Title = "Professional Gymnast Coach"
                        },
                        new
                        {
                            Id = 22,
                            Active = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9524),
                            Name = "Dr. Geovany Keebler",
                            Title = "Professional Gymnast Coach"
                        });
                });

            modelBuilder.Entity("AppointmentScheduler.API.Models.CoachSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoachSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = 1,
                            CoachId = 1,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9664),
                            EndTime = "5:00 PM",
                            Name = "Wednesday",
                            StartTime = "8:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 2,
                            Active = 1,
                            CoachId = 2,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9666),
                            EndTime = "5:30 PM",
                            Name = "Monday",
                            StartTime = "9:00 AM",
                            Timezone = "(GMT-06:00) America/North_Dakota/New_Salem"
                        },
                        new
                        {
                            Id = 3,
                            Active = 1,
                            CoachId = 3,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9666),
                            EndTime = "4:00 PM",
                            Name = "Tuesday",
                            StartTime = "8:00 AM",
                            Timezone = "(GMT-06:00) America/North_Dakota/New_Salem"
                        },
                        new
                        {
                            Id = 4,
                            Active = 1,
                            CoachId = 4,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9668),
                            EndTime = "4:00 PM",
                            Name = "Thursday",
                            StartTime = "9:00 AM",
                            Timezone = "(GMT-06:00) America/North_Dakota/New_Salem"
                        },
                        new
                        {
                            Id = 5,
                            Active = 1,
                            CoachId = 5,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9669),
                            EndTime = "2:00 PM",
                            Name = "Friday",
                            StartTime = "7:00 AM",
                            Timezone = "(GMT-06:00) America/North_Dakota/New_Salem"
                        },
                        new
                        {
                            Id = 6,
                            Active = 1,
                            CoachId = 6,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9670),
                            EndTime = "10:00 AM",
                            Name = "Tuesday",
                            StartTime = "8:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 7,
                            Active = 1,
                            CoachId = 7,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9671),
                            EndTime = "6:00 PM",
                            Name = "Wednesday",
                            StartTime = "11:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 8,
                            Active = 1,
                            CoachId = 8,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9672),
                            EndTime = "3:00 PM",
                            Name = "Saturday",
                            StartTime = "9:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 9,
                            Active = 1,
                            CoachId = 9,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9673),
                            EndTime = "3:00 PM",
                            Name = "Sunday",
                            StartTime = "8:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 10,
                            Active = 1,
                            CoachId = 10,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9674),
                            EndTime = "10:00 AM",
                            Name = "Monday",
                            StartTime = "8:00 AM",
                            Timezone = "(GMT-09:00) America/Yakutat"
                        },
                        new
                        {
                            Id = 11,
                            Active = 1,
                            CoachId = 11,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9674),
                            EndTime = "1:00 PM",
                            Name = "Tuesday",
                            StartTime = "11:00 AM",
                            Timezone = "(GMT-09:00) America/Yakutat"
                        },
                        new
                        {
                            Id = 12,
                            Active = 1,
                            CoachId = 12,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9675),
                            EndTime = "10:00 AM",
                            Name = "Wednesday",
                            StartTime = "8:00 AM",
                            Timezone = "(GMT-09:00) America/Yakutat"
                        },
                        new
                        {
                            Id = 13,
                            Active = 1,
                            CoachId = 13,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9676),
                            EndTime = "11:00 AM",
                            Name = "Saturday",
                            StartTime = "8:00 AM",
                            Timezone = "(GMT-09:00) America/Yakutat"
                        },
                        new
                        {
                            Id = 14,
                            Active = 1,
                            CoachId = 14,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9677),
                            EndTime = "9:00 AM",
                            Name = "Sunday",
                            StartTime = "7:00 AM",
                            Timezone = "(GMT-09:00) America/Yakutat"
                        },
                        new
                        {
                            Id = 15,
                            Active = 1,
                            CoachId = 15,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9678),
                            EndTime = "3:00 PM",
                            Name = "Monday",
                            StartTime = "9:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 16,
                            Active = 1,
                            CoachId = 16,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9679),
                            EndTime = "1:00 PM",
                            Name = "Tuesday",
                            StartTime = "6:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 17,
                            Active = 1,
                            CoachId = 17,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9680),
                            EndTime = "11:00 AM",
                            Name = "Wednesday",
                            StartTime = "6:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 18,
                            Active = 1,
                            CoachId = 18,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9680),
                            EndTime = "12:00 PM",
                            Name = "Friday",
                            StartTime = "8:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 19,
                            Active = 1,
                            CoachId = 19,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9681),
                            EndTime = "4:00 PM",
                            Name = "Saturday",
                            StartTime = "9:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 20,
                            Active = 1,
                            CoachId = 20,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9682),
                            EndTime = "10:00 AM",
                            Name = "Sunday",
                            StartTime = "8:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 21,
                            Active = 1,
                            CoachId = 21,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9683),
                            EndTime = "2:00 PM",
                            Name = "Thursday",
                            StartTime = "7:00 AM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        },
                        new
                        {
                            Id = 22,
                            Active = 1,
                            CoachId = 22,
                            CreatedDate = new DateTime(2022, 9, 21, 15, 41, 51, 544, DateTimeKind.Local).AddTicks(9684),
                            EndTime = "5:00 PM",
                            Name = "Thursday",
                            StartTime = "3:00 PM",
                            Timezone = "(GMT-06:00) Central Time (US & Canada)"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
